import { Injectable } from '@angular/core';
import { Book } from './book.model';

@Injectable({
  providedIn: 'root',
})
export class BookService {
  getBooks(): Book[] {
    return [
      {
       
        title: 'Introduction to Programming',
        author: 'Nick Samoylov',
        AboutThisBook: 'Get a solid understanding of Java fundamentals to master programming through a series of practical steps',
        rating: 4,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/759691206/original/432x574/c77c89d9e9/1723842710?v=1',
      },
      {
       
        title: 'C++ Programming Language',
        author: 'Bjarne Stroustrup',
        AboutThisBook: 'Provides up to date and complete coverage of all C++ language features',
        rating: 5,
        imageUrl: 'https://imgv2-1-f.scribdassets.com/img/word_document/528489839/original/432x574/524306d4b2/1677228726?v=1',
      },
      {
      
        title: 'Angular Development',
        author: 'Sukesh Marla',
        AboutThisBook: 'The book begins with building a strong foundation on the concepts of web application development ',
        rating: 4,
        imageUrl: 'https://imgv2-1-f.scribdassets.com/img/word_document/571963713/original/432x574/7e932397b7/1700118627?v=1',
      },
      {
       
        title: 'Python Programmming',
        author: ' Ramsey Hamilton',
        AboutThisBook: 'Python is a beautiful computer language. It is simple, and it is intuitive. ',
        rating: 3,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/315613600/original/432x574/60a0c13836/1698684512?v=1',
      },
      {
       
        title: 'Mastering Git',
        author: 'Jakub Narębski',
        AboutThisBook: 'Set up Git for solo and collaborative development',
        rating: 4,
        imageUrl: 'https://imgv2-1-f.scribdassets.com/img/word_document/759703218/original/432x574/dbc8225055/1723846801?v=1',
      },
      {
        
        title: 'Python Data Structures and Algorithms',
        author: 'Benjamin Baka',
        AboutThisBook: 'Get a better understanding of advanced Python concepts such as big-o notation, dynamic programming, and functional data structures.',
        rating: 5,
        imageUrl: 'https://imgv2-1-f.scribdassets.com/img/word_document/382519369/original/432x574/f6ae997efb/1617225378?v=1',
      },
      {
        
        title: 'SQL',
        author: 'Brandon Cooper',
        AboutThisBook: ' start creating and using SQL databases, even if you have no prior programming experience.',
        rating: 4,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/437508313/original/432x574/2ef10d3d82/1681952639?v=1',
      },
      {
        
        title: 'Prototyping Interfaces with Figma',
        author: 'Fabio Staiano',
        AboutThisBook: 'learn the art of creating compelling interfaces using Figma? Look no further! The highly anticipated new edition is here to transform your creative journey.',
        rating: 5,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/759724125/original/432x574/1cd3f73502/1723854643?v=1',
      },
      {
        
        title: 'React Projects',
        author: 'Prototyping Interfaces with Figma',
        AboutThisBook: 'Build cross-platform applications of varying complexity for the web, mobile, and VR devices using React tooling',
        rating: 5,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/498886142/original/432x574/51b3da49cd/1617234470?v=1',
      },
      {
        
        title: 'Data Analytics ',
        author: ' Anthony S. Williams',
        AboutThisBook: 'Knowing the data generated by your business every day is a key to success in the Data Analytic World that you are competing in.',
        rating: 2,
        imageUrl: 'https://imgv2-2-f.scribdassets.com/img/word_document/518686312/original/432x574/ec19ae8bcd/1730366468?v=1',
      },
    ];
  }
}
